# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 091bf35a5d369af8a8c5443308f51bc72933b61b12056bffdb042a7342aa90c349ccb2b3dbb93e385440edccb57b69fb0c5713ca9e233f7f7460e85009eaba84

test:
  secret_key_base: 3b8c28065591ae15e25aaab4e13b6f2c936d55f8c8964f3bec0c32c239c309ce30199257e766e54db8a6cb3a525bab0d078594f2cbd85e6402b8e538c3d1baed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
